### ISSUE TITLE
Feedback Request: NTW-01 OSI Model

### ISSUE THREAD

**Issue by benbui797** [TechGrounds-Cloud8/cloud8-benbui797#13]
**Feedback Request NTW-01**
Permalink to file: [NTW-01](https://github.com/TechGrounds-Cloud8/cloud8-benbui797/blob/main/03_Networking_1/NTW-01_OSI_stack.md)

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by Killian97** [comment]
duidelijk de opdracht in eigen manier begrepen. ik zelf heb gelijk wat geleerd.

**Comment by yismailmo** [comment]
**Summary**
- Does the summary describe the subject matter fully?yes
- Is the summary written in own words?yes
- Is there crucial information missing in the summary?no
- Is the description clear enough?yes

**Key Terminology**
- Are there missing key terms?no
- Are the key terms explained well?yes

**Sources**
- Are the sources mentioned?yes
- Are the mentioned sources correct?yes

**Excercise**
(Where applicable)
- Is the result correct?yes
- Are the experienced problems and solutions described well?

**Comment by se0727** [comment]
Goede uitwerking, uitgebreid.
